apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
  data:
    - secretKey: MONGO_URI
      remoteRef:
        key: mongodb-atlas-uri